### ISSUE TITLE
每次重新打开vscode都会打开配置页面

### ISSUE THREAD

**Issue by CnData07** [LiteLScript-Dev/LiteLoaderSE-Aids#12]
每次重新打开vscode都会打开配置页面：
![image](https://user-images.githubusercontent.com/103437534/192494752-00461ea9-438d-455b-a4d0-b20cd0838514.png)
版本：v2.1.5

**Comment by moxisuki** [comment]
请注意库存放地址是否为src的父级目录

**Comment by CnData07** [comment]
已解决
