### ISSUE TITLE
不齊全和Bug

### ISSUE THREAD

**Issue by omscsamilcup** [LiteLScript-Dev/LiteLoaderSE-Aids#13]
mc.regPlayerCmd()會出現mc.~~regPlayerCmd~~()
![image](https://user-images.githubusercontent.com/112487226/196968957-40e1e5bf-a059-465b-a81b-69a0db2e930f.png)

mc.regConsoleCmd不會自動出現
![image](https://user-images.githubusercontent.com/112487226/196969461-5c4ae6ce-6ae2-4c90-8004-e4f341e57cef.png)

![image](https://user-images.githubusercontent.com/112487226/196969538-9c1d8d39-6951-43d1-ad52-fee53851e7ec.png)

**Comment by omscsamilcup** [comment]
PS:這些功能之前是有的

**Comment by moxisuki** [comment]
因为在lib中未进行定义 ，请转移issue https://github.com/LiteLScript-Dev/HelperLib/blob/3f6d9262776393210819ec0c590bc302ab6d8487/src/GameAPI/Command/mc.d.ts
