### ISSUE TITLE
maybe im just special. here is the error log though

### ISSUE THREAD

**Issue by PaynMusic** [LiteLScript-Dev/LiteLoaderSE-Aids#15]
1/21/2023 7:53:07 PM - Microsoft VSIX Installer
1/21/2023 7:53:07 PM - -------------------------------------------
1/21/2023 7:53:07 PM - vsixinstaller.exe version:
1/21/2023 7:53:07 PM - 17.4.2120
1/21/2023 7:53:07 PM - -------------------------------------------
1/21/2023 7:53:07 PM - Command line parameters:
1/21/2023 7:53:07 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\t_har\Desktop\mc.advanced\plugpacks\moxicat.LLScriptHelper-2.1.5.vsix
1/21/2023 7:53:07 PM - -------------------------------------------
1/21/2023 7:53:07 PM - Microsoft VSIX Installer
1/21/2023 7:53:07 PM - -------------------------------------------
1/21/2023 7:53:07 PM - Skipping product Microsoft.VisualStudio.Product.BuildTools (a54c56ff) since it does not support extensions
1/21/2023 7:53:07 PM - Initializing Install...
1/21/2023 7:53:08 PM - Extension Details...
1/21/2023 7:53:08 PM - 	Identifier         : LLScriptHelper
1/21/2023 7:53:08 PM - 	Name               : LiteLoaderSE-Aids
1/21/2023 7:53:08 PM - 	Author             : moxicat
1/21/2023 7:53:08 PM - 	Version            : 2.1.5
1/21/2023 7:53:08 PM - 	Description        : Assist in the development of LLScript's plugin
1/21/2023 7:53:08 PM - 	Locale             : en-US
1/21/2023 7:53:08 PM - 	MoreInfoURL        : 
1/21/2023 7:53:08 PM - 	InstalledByMSI     : False
1/21/2023 7:53:08 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
1/21/2023 7:53:08 PM - 
1/21/2023 7:53:08 PM - 	SignatureState     : Unsigned
1/21/2023 7:53:08 PM - 	Supported Products : 
1/21/2023 7:53:08 PM - 		Microsoft.VisualStudio.Code
1/21/2023 7:53:08 PM - 			Version : 
1/21/2023 7:53:08 PM - 			ProductArchitecture : x86
1/21/2023 7:53:08 PM - 
1/21/2023 7:53:08 PM - 	References         : 
1/21/2023 7:53:08 PM - Signature Details...
1/21/2023 7:53:08 PM - 	Extension is not signed.
1/21/2023 7:53:08 PM - 
1/21/2023 7:53:08 PM - Searching for applicable products...
1/21/2023 7:53:08 PM - Found installed product - Visual Studio Enterprise 2022
1/21/2023 7:53:08 PM - Found installed product - Global Location
1/21/2023 7:53:08 PM - VSIXInstaller.NoApplicableSKUsException: One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by moxisuki** [comment]
You can install it through the marketplace
