### ISSUE TITLE
显示文档工能不能正常工作

### ISSUE THREAD

**Issue by harry-xi** [LiteLScript-Dev/LiteLoaderSE-Aids#6]
使用按钮打开文档会出现照片中的情况，仅出现标题不显示任何内容，此时直接使用浏览器打开文档是正常的
![image](https://user-images.githubusercontent.com/79187160/159127287-ee657008-a5c9-475a-af5b-88d382905746.png)

**Comment by harry-xi** [comment]
这是一个对应本项目旧版本的issue

**Comment by moxisuki** [comment]
> 这是一个对应本项目旧版本的issue

因为ll文档站域名更换，另外建议用新版本，最近会把旧版功能补上，新版本文档查看有了缓存机制速度会更快
