### ISSUE TITLE
向js文件中输入内容就会弹出视窗Docs

### ISSUE THREAD

**Issue by CnData07** [LiteLScript-Dev/LiteLoaderSE-Aids#9]
我在vscode编写llse插件，今天使用LiteLoaderSE-Aids插件进行开发的时候，想改点内容，结果一输入内容就会弹出Docs视窗占满整个窗口，以前从来没出现过。目前的版本是v2.1.2

**Comment by moxisuki** [comment]
> 我在今天使用该插件进行开发的时候，想改点内容，结果一输入内容就会弹出Docs视窗占满整个窗口，以前从来没出现过。目前的版本是v2.1.2

能给我看看vscode本扩展的设置页面吗，Api引用地址这一条

**Comment by CnData07** [comment]
![image](https://user-images.githubusercontent.com/103437534/189295389-906bc7ad-36f6-49c5-a8ae-a7cc607e258b.png)

**Comment by CnData07** [comment]
![image](https://user-images.githubusercontent.com/103437534/189295512-9db67903-9f3e-4f50-a0cd-43381ad79f61.png)

**Comment by CnData07** [comment]
我Extension › Llseaids: JavaScript Api Path，中貌似是空的

**Comment by moxisuki** [comment]
是的，重新配置下补全库即可，这是由于配置项id更改（我的锅）旧配置失效

> 我Extension › Llseaids: JavaScript Api Path，中貌似是空的

**Comment by CnData07** [comment]
已解决，感谢作者
